version: "3.8"
services:
  db:
    image: postgres
    container_name: carbon_db
    env_file:
      - ./server/.env
    ports:
      - "${SERVER_BIND_PORT:-5432}:5432"

  api:
    build: ./server
    container_name: carbon_api
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "${SERVER_BIND_PORT:-8000}:8000"
    volumes:
      - "./server:/var/www/server"

#  web:
#    build: ./web
#    container_name: carbon_web
#    env_file:
#      - ./web/.env.local
#    depends_on:
#      - db
#      - api
#    ports:
#      - "${SERVER_BIND_PORT:-9000}:3000"
#    volumes:
#      - "./web:/var/www/web"

