version: "3.8"
services:
  db:
    image: postgres
    container_name: carbon_db
    env_file:
      - .env
    ports:
      - "5437:5432"

  api:
    build: ./server
    container_name: carbon_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${SERVER_BIND_PORT:-8000}:8000"




