# Generated by Django 4.0.4 on 2022-05-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usage_user_alter_usage_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='user_type',
            new_name='usage_type',
        ),
    ]
