FROM python:3.10.2
LABEL maintainer="koyagabriel@gmail.com"
WORKDIR /var/www/server
COPY requirements.txt /var/www/server
RUN pip install -r requirements.txt
COPY . /var/www/server
ENTRYPOINT ["bash", "./server.sh"]