FROM python:3.10.2
LABEL maintainer="koyagabriel@gmail.com"
WORKDIR /var/www
COPY requirements.txt /var/www
RUN pip install -r requirements.txt
COPY . /var/www
ENTRYPOINT ["python", "manage.py", "runserver"]
CMD ["0.0.0.0:8000"]